---
title: Xiaomei Wang
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: xxx.sjtu.edu.cn
description: ''
baseurl: ''
url: ''
twitter_username: Xiaomei Wang
github_username: WangXiaoMei1
cv_username: My CV
phone: "+86-1xx-xxx-xxx"
markdown: kramdown
