# Site settings
title: "Jingwei Zhao"
email: "zhaojw@sjtu.edu.cn"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: "zhao jingwei"
github_username: "zhaojw1998"
cv_username: "CV"

# Build settings
markdown: kramdown
